apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings-deployment
spec:
  selector:
    matchLabels:
      app: settings
  template:
    metadata:
      labels:
        app: settings
    spec:
      containers:
      - name: settings
        image: Droplet/settings
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: 1
        ports:
        - containerPort: 80
