apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: Droplet/storage
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: 1
        ports:
        - containerPort: 80
