apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-deployment
spec:
  selector:
    matchLabels:
      app: webhooks
  template:
    metadata:
      labels:
        app: webhooks
    spec:
      containers:
      - name: webhooks
        image: Droplet/webhooks
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: 1
        ports:
        - containerPort: 80
